services:
  - type: web
    name: onefill
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
